[[plugins]]
repo = 'Shougo/neomru.vim'
on_path = '.*'

[[plugins]]
repo = 'Shougo/neoyank.vim'
on_path = '.*'
on_event = "InsertEnter"

[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = "InsertEnter"
hook_source = '''
source ~/.vim/plugins/deoplete.rc.vim
'''

[[plugins]]
repo = 'lighttiger2505/deoplete-vim-lsp'
on_event = "InsertEnter"

[[plugins]]
repo = 'fishbullet/deoplete-ruby'
on_ft = 'ruby'

[[plugins]]
repo = 'deoplete-plugins/deoplete-clang'
on_ft = ['c', 'c11', 'cpp']

[[plugins]]
repo = 'Shougo/deoppet.nvim'
on_event = "InsertEnter"
hook_source = '''
source ~/.vim/plugins/deoppet.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'
on_event = "InsertEnter"
depends = ['deoppet.nvim']

[[plugins]]
repo = 'Shougo/unite.vim'
depends = 'neomru.vim'
hook_add = '''
source ~/.vim/plugins/unite.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-endwise'
on_ft = 'ruby'

[[plugins]]
repo = 'fatih/vim-go'
on_ft = 'go'
hook_add = '''
source ~/.vim/plugins/vim-go.rc.vim
'''

[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = 'markdown'
hook_add = '''
source ~/.vim/plugins/vim-markdown.rc.vim
'''

[[plugins]]
repo = 'mzlogin/vim-markdown-toc'
on_ft = 'markdown'

[[plugins]]
repo = 'mattn/vim-maketable'
on_ft = 'markdown'

[[plugins]]
repo = 'Valloric/MatchTagAlways'
on_ft = 'html'

[[plugins]]
repo = 'lervag/vimtex'
on_ft = 'tex'
hook_add = '''
source ~/.vim/plugins/vimtex.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-sqlfmt'
on_ft = 'sql'

[[plugins]]
repo = 'elzr/vim-json'
on_ft = 'json'
hook_add = '''
source ~/.vim/plugins/vim-json.rc.vim
'''

[[plugins]]
repo = 'hashivim/vim-terraform'
on_ft = ['terraform', 'json']
hook_add = '''
source ~/.vim/plugins/vim-terraform.rc.vim
'''
