[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
source ~/.vim/plugins/colorschemes.rc.vim
'''

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
source ~/.vim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/defx.nvim'
hook_add = '''
source ~/.vim/plugins/defx.rc.vim
'''

[[plugins]]
repo = 'kristijanhusak/defx-icons'

[[plugins]]
repo = 'kristijanhusak/defx-git'

[[plugins]]
repo = 'Shougo/denite.nvim'
hook_add = '''
source ~/.vim/plugins/denite.rc.vim
'''

[[plugins]]
repo = 'kmnk/denite-dirmark'

[[plugins]]
repo = 'N0nki/denite-markdown'

[[plugins]]
repo = 'chemzqm/unite-location'

[[plugins]]
repo = 'Shougo/deol.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
source ~/.vim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
depends = ['tpope/vim-fugitive']
repo = 'junegunn/gv.vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-repeat'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'
hook_add = '''
source ~/.vim/plugins/vim-gitgutter.rc.vim
'''

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.vim/plugins/quickrun.rc.vim
'''

[[plugins]]
repo = 'osyo-manga/shabadou.vim'

[[plugins]]
repo = 'osyo-manga/vim-over'

[[plugins]]
repo = 'osyo-manga/vim-anzu'
hook_add = '''
source ~/.vim/plugins/vim-anzu.rc.vim
'''

[[plugins]]
repo = 'tyru/open-browser.vim'
hook_add = '''
source ~/.vim/plugins/open-browser.rc.vim
'''

[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
hook_post_update = 'TSUpdate'
hook_source = '''
source ~/.vim/plugins/nvim-treesitter.rc.vim
'''

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'ackyshake/Spacegray.vim'

[[plugins]]
repo = 'arcticicestudio/nord-vim'

[[plugins]]
repo = 'sainnhe/everforest'

[[plugins]]
repo = 'morhetz/gruvbox'

[[plugins]]
repo = 'elianiva/icy.nvim'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'ryanoasis/vim-devicons'
hook_add = '''
source ~/.vim/plugins/vim-devicons.rc.vim
'''

[[plugins]]
repo = 'mattn/gist-vim'
depends = ['mattn/webapi-vim']
hook_add = '''
source ~/.vim/plugins/gist-vim.rc.vim
'''

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
source ~/.vim/plugins/ale.rc.vim
'''

[[plugins]]
repo = 'kassio/neoterm'
hook_add = '''
source ~/.vim/plugins/neoterm.rc.vim
'''

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.vim/plugins/indentline.rc.vim
'''

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = ['junegunn/fzf']
hook_add = '''
source ~/.vim/plugins/fzf-vim.rc.vim
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --bin'
merged = '0'

[[plugins]]
repo = 'easymotion/vim-easymotion'
hook_add = '''
source ~/.vim/plugins/vim-easymotion.rc.vim
'''

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'
hook_add = '''
source ~/.vim/plugins/vim-lsp.rc.vim
'''

[[plugins]]
repo = 'mattn/vim-lsp-settings'
merged = '0'

[[plugins]]
repo = 'liuchengxu/vista.vim'
hook_add = '''
source ~/.vim/plugins/vista.rc.vim
'''

[[plugins]]
if = "!has('nvim')"
repo = 'haya14busa/is.vim'

[[plugins]]
if = "!has('nvim')"
repo = 'roxma/nvim-yarp'

[[plugins]]
if = "!has('nvim')"
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'wesQ3/vim-windowswap'
hook_add = '''
source ~/.vim/plugins/vim-windowswap.rc.vim
'''
[[plugins]]
repo = 'aserebryakov/vim-todo-lists'

[[plugins]]
repo = 'junegunn/goyo.vim'

[[plugins]]
repo = 'cohama/lexima.vim'
on_i = 1
