[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/vimproc.vim'
build = 'make'

[[plugins]]
repo = 'Shougo/vimshell.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimshell.rc.vim
'''

[[plugins]]
repo = 'Shougo/vimfiler.vim'
hook_add = '''
source ~/.config/nvim/plugins/vimfiler.rc.vim
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']
hook_add = '''
source ~/.config/nvim/plugins/airline.rc.vim
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'Yggdroot/indentLine'
hook_add = '''
source ~/.config/nvim/plugins/indentline.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'lervag/vimtex'
hook_add = '''
source ~/.config/nvim/plugins/vimtex.rc.vim
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'thinca/vim-quickrun'
hook_add = '''
source ~/.config/nvim/plugins/quickrun.rc.vim
'''
