# brew bundle dump

tap "d12frosted/emacs-plus"
tap "homebrew/bundle"
tap "knqyf263/pet"
tap "neovim/neovim"
tap "wez/wezterm"
brew "python@3.13"
brew "ansible"
brew "ansifilter"
brew "autoconf"
brew "libtool"
brew "autogen"
brew "automake"
brew "aws-sam-cli"
brew "awscli"
brew "bottom"
brew "cheat"
brew "ctags"
brew "curl"
brew "eza"
brew "fastfetch"
brew "fish"
brew "fzf"
brew "gcc"
brew "ghostscript"
brew "gibo"
brew "git"
brew "git-lfs"
brew "git-secrets"
brew "go"
brew "gping"
brew "grep"
brew "imagemagick"
brew "jansson"
brew "jq"
brew "lazygit"
brew "lua"
brew "mas"
brew "mecab"
brew "mecab-ipadic"
brew "neovim"
brew "node"
brew "nodebrew"
brew "pandoc"
brew "pipenv"
brew "pyenv"
brew "python@3.9"
brew "rbenv"
brew "ripgrep"
brew "rust"
brew "serverless"
brew "shellcheck"
brew "starship"
brew "tfenv"
brew "the_silver_searcher"
brew "tig"
brew "tika"
brew "tmux"
brew "tmux-xpanes"
brew "typst"
brew "vim"
brew "wget"
brew "d12frosted/emacs-plus/emacs-plus@27"
brew "knqyf263/pet/pet"
cask "1password-cli"
cask "appcleaner"
cask "bettertouchtool"
cask "chatgpt"
cask "chromedriver"
cask "copyq"
cask "docker"
cask "dropbox"
cask "eset-cyber-security"
cask "firefox"
cask "font-cica"
cask "font-hack-nerd-font"
cask "font-hackgen"
cask "font-hackgen-nerd"
cask "ghostty"
cask "gisto"
cask "google-chrome"
cask "google-cloud-sdk"
cask "google-japanese-ime"
cask "hyper"
cask "iterm2"
cask "lepton"
cask "macdown"
cask "neohtop"
cask "neovide"
cask "notion"
cask "popclip"
cask "raycast"
cask "skype"
cask "slack"
cask "visual-studio-code"
cask "vlc"
cask "wave"
cask "wezterm"
cask "zed"
mas "ApolloOne", id: 1044484672
mas "BetterSnapTool", id: 417375580
mas "Calendars", id: 608834326
mas "Day One", id: 1055511498
mas "Disk Speed Test", id: 425264550
mas "Game Of Life", id: 1377718068
mas "GarageBand", id: 682658836
mas "Goodnotes", id: 1444383602
mas "iMovie", id: 408981434
mas "iSuper DVD Ripper", id: 625150797
mas "John's Background Switcher", id: 907640277
mas "Keynote", id: 409183694
mas "Kindle", id: 302584613
mas "LINE", id: 539883307
mas "Magnet", id: 441258766
mas "Marked 2", id: 890031187
mas "MARKETSPEED", id: 946680495
mas "Monosnap", id: 540348655
mas "Notion Web Clipper", id: 1559269364
mas "Numbers", id: 409203825
mas "OneDrive", id: 823766827
mas "Pages", id: 409201541
mas "Reeder", id: 1529448980
mas "RunCat", id: 1429033973
mas "Skitch", id: 425955336
mas "Slack", id: 803453959
mas "Spark", id: 1176895641
mas "Tailscale", id: 1475387142
mas "The Unarchiver", id: 425424353
mas "TickTick", id: 966085870
mas "ToyViewer", id: 414298354
mas "Xcode", id: 497799835
vscode "asvetliakov.vscode-neovim"
vscode "be5invis.toml"
vscode "beeverfeever.kanagawa-vscode"
vscode "cocopon.iceberg-theme"
vscode "davidanson.vscode-markdownlint"
vscode "donjayamanne.githistory"
vscode "golang.go"
vscode "grapecity.gc-excelviewer"
vscode "harg.iceberg"
vscode "hashicorp.terraform"
vscode "hediet.vscode-drawio"
vscode "jdinhlife.gruvbox"
vscode "marp-team.marp-vscode"
vscode "mhutchie.git-graph"
vscode "ms-azuretools.vscode-docker"
vscode "ms-ceintl.vscode-language-pack-ja"
vscode "ms-python.debugpy"
vscode "ms-python.flake8"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-toolsai.jupyter"
vscode "ms-toolsai.jupyter-keymap"
vscode "ms-toolsai.jupyter-renderers"
vscode "ms-toolsai.vscode-jupyter-cell-tags"
vscode "ms-toolsai.vscode-jupyter-slideshow"
vscode "ms-vscode-remote.remote-containers"
vscode "ms-vscode-remote.remote-ssh"
vscode "ms-vscode-remote.remote-ssh-edit"
vscode "ms-vscode-remote.remote-wsl"
vscode "ms-vscode-remote.vscode-remote-extensionpack"
vscode "ms-vscode.cpptools"
vscode "ms-vscode.powershell"
vscode "ms-vscode.remote-explorer"
vscode "ms-vscode.remote-server"
vscode "ms-vsliveshare.vsliveshare"
vscode "octref.vetur"
vscode "s-nlf-fh.glassit"
vscode "yzane.markdown-pdf"
v
